/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.polysteam.plateforme.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Événement émis par la plateforme lors de l'évaluation d'un jeu par un joueur */
@org.apache.avro.specific.AvroGenerated
public class EvaluationEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3059900743018246768L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EvaluationEvent\",\"namespace\":\"com.polysteam.plateforme.events\",\"doc\":\"Événement émis par la plateforme lors de l'évaluation d'un jeu par un joueur\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"Identifiant unique de l'événement\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Timestamp de création de l'événement (epoch millis)\"},{\"name\":\"evaluationId\",\"type\":\"string\",\"doc\":\"Identifiant unique de l'évaluation\"},{\"name\":\"jeuId\",\"type\":\"string\",\"doc\":\"Identifiant du jeu évalué\"},{\"name\":\"titreJeu\",\"type\":\"string\",\"doc\":\"Titre du jeu évalué\"},{\"name\":\"editeurId\",\"type\":\"string\",\"doc\":\"Identifiant de l'éditeur concerné\"},{\"name\":\"pseudoJoueur\",\"type\":\"string\",\"doc\":\"Pseudo du joueur qui évalue\"},{\"name\":\"note\",\"type\":\"int\",\"doc\":\"Note attribuée (ex: sur 10 ou 20)\"},{\"name\":\"commentaire\",\"type\":[\"null\",\"string\"],\"doc\":\"Commentaire textuel (optionnel)\",\"default\":null},{\"name\":\"tempsDeJeuEnMinutes\",\"type\":\"long\",\"doc\":\"Temps de jeu du joueur au moment de l'évaluation\"},{\"name\":\"versionJeuEvaluee\",\"type\":\"string\",\"doc\":\"Version du jeu lors de l'évaluation\"},{\"name\":\"datePublication\",\"type\":\"long\",\"doc\":\"Date de publication de l'évaluation (epoch millis)\"},{\"name\":\"recommande\",\"type\":\"boolean\",\"doc\":\"True si le joueur recommande le jeu\"},{\"name\":\"aspectsPositifs\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Liste des aspects positifs mentionnés\",\"default\":[]},{\"name\":\"aspectsNegatifs\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"Liste des aspects négatifs mentionnés\",\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EvaluationEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EvaluationEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EvaluationEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EvaluationEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EvaluationEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EvaluationEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EvaluationEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EvaluationEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EvaluationEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identifiant unique de l'événement */
  private java.lang.CharSequence eventId;
  /** Timestamp de création de l'événement (epoch millis) */
  private long timestamp;
  /** Identifiant unique de l'évaluation */
  private java.lang.CharSequence evaluationId;
  /** Identifiant du jeu évalué */
  private java.lang.CharSequence jeuId;
  /** Titre du jeu évalué */
  private java.lang.CharSequence titreJeu;
  /** Identifiant de l'éditeur concerné */
  private java.lang.CharSequence editeurId;
  /** Pseudo du joueur qui évalue */
  private java.lang.CharSequence pseudoJoueur;
  /** Note attribuée (ex: sur 10 ou 20) */
  private int note;
  /** Commentaire textuel (optionnel) */
  private java.lang.CharSequence commentaire;
  /** Temps de jeu du joueur au moment de l'évaluation */
  private long tempsDeJeuEnMinutes;
  /** Version du jeu lors de l'évaluation */
  private java.lang.CharSequence versionJeuEvaluee;
  /** Date de publication de l'évaluation (epoch millis) */
  private long datePublication;
  /** True si le joueur recommande le jeu */
  private boolean recommande;
  /** Liste des aspects positifs mentionnés */
  private java.util.List<java.lang.CharSequence> aspectsPositifs;
  /** Liste des aspects négatifs mentionnés */
  private java.util.List<java.lang.CharSequence> aspectsNegatifs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EvaluationEvent() {}

  /**
   * All-args constructor.
   * @param eventId Identifiant unique de l'événement
   * @param timestamp Timestamp de création de l'événement (epoch millis)
   * @param evaluationId Identifiant unique de l'évaluation
   * @param jeuId Identifiant du jeu évalué
   * @param titreJeu Titre du jeu évalué
   * @param editeurId Identifiant de l'éditeur concerné
   * @param pseudoJoueur Pseudo du joueur qui évalue
   * @param note Note attribuée (ex: sur 10 ou 20)
   * @param commentaire Commentaire textuel (optionnel)
   * @param tempsDeJeuEnMinutes Temps de jeu du joueur au moment de l'évaluation
   * @param versionJeuEvaluee Version du jeu lors de l'évaluation
   * @param datePublication Date de publication de l'évaluation (epoch millis)
   * @param recommande True si le joueur recommande le jeu
   * @param aspectsPositifs Liste des aspects positifs mentionnés
   * @param aspectsNegatifs Liste des aspects négatifs mentionnés
   */
  public EvaluationEvent(java.lang.CharSequence eventId, java.lang.Long timestamp, java.lang.CharSequence evaluationId, java.lang.CharSequence jeuId, java.lang.CharSequence titreJeu, java.lang.CharSequence editeurId, java.lang.CharSequence pseudoJoueur, java.lang.Integer note, java.lang.CharSequence commentaire, java.lang.Long tempsDeJeuEnMinutes, java.lang.CharSequence versionJeuEvaluee, java.lang.Long datePublication, java.lang.Boolean recommande, java.util.List<java.lang.CharSequence> aspectsPositifs, java.util.List<java.lang.CharSequence> aspectsNegatifs) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.evaluationId = evaluationId;
    this.jeuId = jeuId;
    this.titreJeu = titreJeu;
    this.editeurId = editeurId;
    this.pseudoJoueur = pseudoJoueur;
    this.note = note;
    this.commentaire = commentaire;
    this.tempsDeJeuEnMinutes = tempsDeJeuEnMinutes;
    this.versionJeuEvaluee = versionJeuEvaluee;
    this.datePublication = datePublication;
    this.recommande = recommande;
    this.aspectsPositifs = aspectsPositifs;
    this.aspectsNegatifs = aspectsNegatifs;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return evaluationId;
    case 3: return jeuId;
    case 4: return titreJeu;
    case 5: return editeurId;
    case 6: return pseudoJoueur;
    case 7: return note;
    case 8: return commentaire;
    case 9: return tempsDeJeuEnMinutes;
    case 10: return versionJeuEvaluee;
    case 11: return datePublication;
    case 12: return recommande;
    case 13: return aspectsPositifs;
    case 14: return aspectsNegatifs;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: evaluationId = (java.lang.CharSequence)value$; break;
    case 3: jeuId = (java.lang.CharSequence)value$; break;
    case 4: titreJeu = (java.lang.CharSequence)value$; break;
    case 5: editeurId = (java.lang.CharSequence)value$; break;
    case 6: pseudoJoueur = (java.lang.CharSequence)value$; break;
    case 7: note = (java.lang.Integer)value$; break;
    case 8: commentaire = (java.lang.CharSequence)value$; break;
    case 9: tempsDeJeuEnMinutes = (java.lang.Long)value$; break;
    case 10: versionJeuEvaluee = (java.lang.CharSequence)value$; break;
    case 11: datePublication = (java.lang.Long)value$; break;
    case 12: recommande = (java.lang.Boolean)value$; break;
    case 13: aspectsPositifs = (java.util.List<java.lang.CharSequence>)value$; break;
    case 14: aspectsNegatifs = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return Identifiant unique de l'événement
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * Identifiant unique de l'événement
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp de création de l'événement (epoch millis)
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp de création de l'événement (epoch millis)
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'evaluationId' field.
   * @return Identifiant unique de l'évaluation
   */
  public java.lang.CharSequence getEvaluationId() {
    return evaluationId;
  }


  /**
   * Sets the value of the 'evaluationId' field.
   * Identifiant unique de l'évaluation
   * @param value the value to set.
   */
  public void setEvaluationId(java.lang.CharSequence value) {
    this.evaluationId = value;
  }

  /**
   * Gets the value of the 'jeuId' field.
   * @return Identifiant du jeu évalué
   */
  public java.lang.CharSequence getJeuId() {
    return jeuId;
  }


  /**
   * Sets the value of the 'jeuId' field.
   * Identifiant du jeu évalué
   * @param value the value to set.
   */
  public void setJeuId(java.lang.CharSequence value) {
    this.jeuId = value;
  }

  /**
   * Gets the value of the 'titreJeu' field.
   * @return Titre du jeu évalué
   */
  public java.lang.CharSequence getTitreJeu() {
    return titreJeu;
  }


  /**
   * Sets the value of the 'titreJeu' field.
   * Titre du jeu évalué
   * @param value the value to set.
   */
  public void setTitreJeu(java.lang.CharSequence value) {
    this.titreJeu = value;
  }

  /**
   * Gets the value of the 'editeurId' field.
   * @return Identifiant de l'éditeur concerné
   */
  public java.lang.CharSequence getEditeurId() {
    return editeurId;
  }


  /**
   * Sets the value of the 'editeurId' field.
   * Identifiant de l'éditeur concerné
   * @param value the value to set.
   */
  public void setEditeurId(java.lang.CharSequence value) {
    this.editeurId = value;
  }

  /**
   * Gets the value of the 'pseudoJoueur' field.
   * @return Pseudo du joueur qui évalue
   */
  public java.lang.CharSequence getPseudoJoueur() {
    return pseudoJoueur;
  }


  /**
   * Sets the value of the 'pseudoJoueur' field.
   * Pseudo du joueur qui évalue
   * @param value the value to set.
   */
  public void setPseudoJoueur(java.lang.CharSequence value) {
    this.pseudoJoueur = value;
  }

  /**
   * Gets the value of the 'note' field.
   * @return Note attribuée (ex: sur 10 ou 20)
   */
  public int getNote() {
    return note;
  }


  /**
   * Sets the value of the 'note' field.
   * Note attribuée (ex: sur 10 ou 20)
   * @param value the value to set.
   */
  public void setNote(int value) {
    this.note = value;
  }

  /**
   * Gets the value of the 'commentaire' field.
   * @return Commentaire textuel (optionnel)
   */
  public java.lang.CharSequence getCommentaire() {
    return commentaire;
  }


  /**
   * Sets the value of the 'commentaire' field.
   * Commentaire textuel (optionnel)
   * @param value the value to set.
   */
  public void setCommentaire(java.lang.CharSequence value) {
    this.commentaire = value;
  }

  /**
   * Gets the value of the 'tempsDeJeuEnMinutes' field.
   * @return Temps de jeu du joueur au moment de l'évaluation
   */
  public long getTempsDeJeuEnMinutes() {
    return tempsDeJeuEnMinutes;
  }


  /**
   * Sets the value of the 'tempsDeJeuEnMinutes' field.
   * Temps de jeu du joueur au moment de l'évaluation
   * @param value the value to set.
   */
  public void setTempsDeJeuEnMinutes(long value) {
    this.tempsDeJeuEnMinutes = value;
  }

  /**
   * Gets the value of the 'versionJeuEvaluee' field.
   * @return Version du jeu lors de l'évaluation
   */
  public java.lang.CharSequence getVersionJeuEvaluee() {
    return versionJeuEvaluee;
  }


  /**
   * Sets the value of the 'versionJeuEvaluee' field.
   * Version du jeu lors de l'évaluation
   * @param value the value to set.
   */
  public void setVersionJeuEvaluee(java.lang.CharSequence value) {
    this.versionJeuEvaluee = value;
  }

  /**
   * Gets the value of the 'datePublication' field.
   * @return Date de publication de l'évaluation (epoch millis)
   */
  public long getDatePublication() {
    return datePublication;
  }


  /**
   * Sets the value of the 'datePublication' field.
   * Date de publication de l'évaluation (epoch millis)
   * @param value the value to set.
   */
  public void setDatePublication(long value) {
    this.datePublication = value;
  }

  /**
   * Gets the value of the 'recommande' field.
   * @return True si le joueur recommande le jeu
   */
  public boolean getRecommande() {
    return recommande;
  }


  /**
   * Sets the value of the 'recommande' field.
   * True si le joueur recommande le jeu
   * @param value the value to set.
   */
  public void setRecommande(boolean value) {
    this.recommande = value;
  }

  /**
   * Gets the value of the 'aspectsPositifs' field.
   * @return Liste des aspects positifs mentionnés
   */
  public java.util.List<java.lang.CharSequence> getAspectsPositifs() {
    return aspectsPositifs;
  }


  /**
   * Sets the value of the 'aspectsPositifs' field.
   * Liste des aspects positifs mentionnés
   * @param value the value to set.
   */
  public void setAspectsPositifs(java.util.List<java.lang.CharSequence> value) {
    this.aspectsPositifs = value;
  }

  /**
   * Gets the value of the 'aspectsNegatifs' field.
   * @return Liste des aspects négatifs mentionnés
   */
  public java.util.List<java.lang.CharSequence> getAspectsNegatifs() {
    return aspectsNegatifs;
  }


  /**
   * Sets the value of the 'aspectsNegatifs' field.
   * Liste des aspects négatifs mentionnés
   * @param value the value to set.
   */
  public void setAspectsNegatifs(java.util.List<java.lang.CharSequence> value) {
    this.aspectsNegatifs = value;
  }

  /**
   * Creates a new EvaluationEvent RecordBuilder.
   * @return A new EvaluationEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.EvaluationEvent.Builder newBuilder() {
    return new com.polysteam.plateforme.events.EvaluationEvent.Builder();
  }

  /**
   * Creates a new EvaluationEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EvaluationEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.EvaluationEvent.Builder newBuilder(com.polysteam.plateforme.events.EvaluationEvent.Builder other) {
    if (other == null) {
      return new com.polysteam.plateforme.events.EvaluationEvent.Builder();
    } else {
      return new com.polysteam.plateforme.events.EvaluationEvent.Builder(other);
    }
  }

  /**
   * Creates a new EvaluationEvent RecordBuilder by copying an existing EvaluationEvent instance.
   * @param other The existing instance to copy.
   * @return A new EvaluationEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.EvaluationEvent.Builder newBuilder(com.polysteam.plateforme.events.EvaluationEvent other) {
    if (other == null) {
      return new com.polysteam.plateforme.events.EvaluationEvent.Builder();
    } else {
      return new com.polysteam.plateforme.events.EvaluationEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for EvaluationEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EvaluationEvent>
    implements org.apache.avro.data.RecordBuilder<EvaluationEvent> {

    /** Identifiant unique de l'événement */
    private java.lang.CharSequence eventId;
    /** Timestamp de création de l'événement (epoch millis) */
    private long timestamp;
    /** Identifiant unique de l'évaluation */
    private java.lang.CharSequence evaluationId;
    /** Identifiant du jeu évalué */
    private java.lang.CharSequence jeuId;
    /** Titre du jeu évalué */
    private java.lang.CharSequence titreJeu;
    /** Identifiant de l'éditeur concerné */
    private java.lang.CharSequence editeurId;
    /** Pseudo du joueur qui évalue */
    private java.lang.CharSequence pseudoJoueur;
    /** Note attribuée (ex: sur 10 ou 20) */
    private int note;
    /** Commentaire textuel (optionnel) */
    private java.lang.CharSequence commentaire;
    /** Temps de jeu du joueur au moment de l'évaluation */
    private long tempsDeJeuEnMinutes;
    /** Version du jeu lors de l'évaluation */
    private java.lang.CharSequence versionJeuEvaluee;
    /** Date de publication de l'évaluation (epoch millis) */
    private long datePublication;
    /** True si le joueur recommande le jeu */
    private boolean recommande;
    /** Liste des aspects positifs mentionnés */
    private java.util.List<java.lang.CharSequence> aspectsPositifs;
    /** Liste des aspects négatifs mentionnés */
    private java.util.List<java.lang.CharSequence> aspectsNegatifs;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.polysteam.plateforme.events.EvaluationEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.evaluationId)) {
        this.evaluationId = data().deepCopy(fields()[2].schema(), other.evaluationId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.jeuId)) {
        this.jeuId = data().deepCopy(fields()[3].schema(), other.jeuId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.titreJeu)) {
        this.titreJeu = data().deepCopy(fields()[4].schema(), other.titreJeu);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.editeurId)) {
        this.editeurId = data().deepCopy(fields()[5].schema(), other.editeurId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.pseudoJoueur)) {
        this.pseudoJoueur = data().deepCopy(fields()[6].schema(), other.pseudoJoueur);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.note)) {
        this.note = data().deepCopy(fields()[7].schema(), other.note);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.commentaire)) {
        this.commentaire = data().deepCopy(fields()[8].schema(), other.commentaire);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.tempsDeJeuEnMinutes)) {
        this.tempsDeJeuEnMinutes = data().deepCopy(fields()[9].schema(), other.tempsDeJeuEnMinutes);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.versionJeuEvaluee)) {
        this.versionJeuEvaluee = data().deepCopy(fields()[10].schema(), other.versionJeuEvaluee);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.datePublication)) {
        this.datePublication = data().deepCopy(fields()[11].schema(), other.datePublication);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.recommande)) {
        this.recommande = data().deepCopy(fields()[12].schema(), other.recommande);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.aspectsPositifs)) {
        this.aspectsPositifs = data().deepCopy(fields()[13].schema(), other.aspectsPositifs);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.aspectsNegatifs)) {
        this.aspectsNegatifs = data().deepCopy(fields()[14].schema(), other.aspectsNegatifs);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing EvaluationEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.polysteam.plateforme.events.EvaluationEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.evaluationId)) {
        this.evaluationId = data().deepCopy(fields()[2].schema(), other.evaluationId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.jeuId)) {
        this.jeuId = data().deepCopy(fields()[3].schema(), other.jeuId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.titreJeu)) {
        this.titreJeu = data().deepCopy(fields()[4].schema(), other.titreJeu);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.editeurId)) {
        this.editeurId = data().deepCopy(fields()[5].schema(), other.editeurId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.pseudoJoueur)) {
        this.pseudoJoueur = data().deepCopy(fields()[6].schema(), other.pseudoJoueur);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.note)) {
        this.note = data().deepCopy(fields()[7].schema(), other.note);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.commentaire)) {
        this.commentaire = data().deepCopy(fields()[8].schema(), other.commentaire);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.tempsDeJeuEnMinutes)) {
        this.tempsDeJeuEnMinutes = data().deepCopy(fields()[9].schema(), other.tempsDeJeuEnMinutes);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.versionJeuEvaluee)) {
        this.versionJeuEvaluee = data().deepCopy(fields()[10].schema(), other.versionJeuEvaluee);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.datePublication)) {
        this.datePublication = data().deepCopy(fields()[11].schema(), other.datePublication);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.recommande)) {
        this.recommande = data().deepCopy(fields()[12].schema(), other.recommande);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.aspectsPositifs)) {
        this.aspectsPositifs = data().deepCopy(fields()[13].schema(), other.aspectsPositifs);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.aspectsNegatifs)) {
        this.aspectsNegatifs = data().deepCopy(fields()[14].schema(), other.aspectsNegatifs);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * Identifiant unique de l'événement
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp de création de l'événement (epoch millis)
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'evaluationId' field.
      * Identifiant unique de l'évaluation
      * @return The value.
      */
    public java.lang.CharSequence getEvaluationId() {
      return evaluationId;
    }


    /**
      * Sets the value of the 'evaluationId' field.
      * Identifiant unique de l'évaluation
      * @param value The value of 'evaluationId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setEvaluationId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.evaluationId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'evaluationId' field has been set.
      * Identifiant unique de l'évaluation
      * @return True if the 'evaluationId' field has been set, false otherwise.
      */
    public boolean hasEvaluationId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'evaluationId' field.
      * Identifiant unique de l'évaluation
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearEvaluationId() {
      evaluationId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'jeuId' field.
      * Identifiant du jeu évalué
      * @return The value.
      */
    public java.lang.CharSequence getJeuId() {
      return jeuId;
    }


    /**
      * Sets the value of the 'jeuId' field.
      * Identifiant du jeu évalué
      * @param value The value of 'jeuId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setJeuId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.jeuId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'jeuId' field has been set.
      * Identifiant du jeu évalué
      * @return True if the 'jeuId' field has been set, false otherwise.
      */
    public boolean hasJeuId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'jeuId' field.
      * Identifiant du jeu évalué
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearJeuId() {
      jeuId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'titreJeu' field.
      * Titre du jeu évalué
      * @return The value.
      */
    public java.lang.CharSequence getTitreJeu() {
      return titreJeu;
    }


    /**
      * Sets the value of the 'titreJeu' field.
      * Titre du jeu évalué
      * @param value The value of 'titreJeu'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setTitreJeu(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.titreJeu = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'titreJeu' field has been set.
      * Titre du jeu évalué
      * @return True if the 'titreJeu' field has been set, false otherwise.
      */
    public boolean hasTitreJeu() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'titreJeu' field.
      * Titre du jeu évalué
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearTitreJeu() {
      titreJeu = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @return The value.
      */
    public java.lang.CharSequence getEditeurId() {
      return editeurId;
    }


    /**
      * Sets the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @param value The value of 'editeurId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setEditeurId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.editeurId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'editeurId' field has been set.
      * Identifiant de l'éditeur concerné
      * @return True if the 'editeurId' field has been set, false otherwise.
      */
    public boolean hasEditeurId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearEditeurId() {
      editeurId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'pseudoJoueur' field.
      * Pseudo du joueur qui évalue
      * @return The value.
      */
    public java.lang.CharSequence getPseudoJoueur() {
      return pseudoJoueur;
    }


    /**
      * Sets the value of the 'pseudoJoueur' field.
      * Pseudo du joueur qui évalue
      * @param value The value of 'pseudoJoueur'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setPseudoJoueur(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.pseudoJoueur = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'pseudoJoueur' field has been set.
      * Pseudo du joueur qui évalue
      * @return True if the 'pseudoJoueur' field has been set, false otherwise.
      */
    public boolean hasPseudoJoueur() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'pseudoJoueur' field.
      * Pseudo du joueur qui évalue
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearPseudoJoueur() {
      pseudoJoueur = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'note' field.
      * Note attribuée (ex: sur 10 ou 20)
      * @return The value.
      */
    public int getNote() {
      return note;
    }


    /**
      * Sets the value of the 'note' field.
      * Note attribuée (ex: sur 10 ou 20)
      * @param value The value of 'note'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setNote(int value) {
      validate(fields()[7], value);
      this.note = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'note' field has been set.
      * Note attribuée (ex: sur 10 ou 20)
      * @return True if the 'note' field has been set, false otherwise.
      */
    public boolean hasNote() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'note' field.
      * Note attribuée (ex: sur 10 ou 20)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearNote() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'commentaire' field.
      * Commentaire textuel (optionnel)
      * @return The value.
      */
    public java.lang.CharSequence getCommentaire() {
      return commentaire;
    }


    /**
      * Sets the value of the 'commentaire' field.
      * Commentaire textuel (optionnel)
      * @param value The value of 'commentaire'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setCommentaire(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.commentaire = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'commentaire' field has been set.
      * Commentaire textuel (optionnel)
      * @return True if the 'commentaire' field has been set, false otherwise.
      */
    public boolean hasCommentaire() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'commentaire' field.
      * Commentaire textuel (optionnel)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearCommentaire() {
      commentaire = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'tempsDeJeuEnMinutes' field.
      * Temps de jeu du joueur au moment de l'évaluation
      * @return The value.
      */
    public long getTempsDeJeuEnMinutes() {
      return tempsDeJeuEnMinutes;
    }


    /**
      * Sets the value of the 'tempsDeJeuEnMinutes' field.
      * Temps de jeu du joueur au moment de l'évaluation
      * @param value The value of 'tempsDeJeuEnMinutes'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setTempsDeJeuEnMinutes(long value) {
      validate(fields()[9], value);
      this.tempsDeJeuEnMinutes = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'tempsDeJeuEnMinutes' field has been set.
      * Temps de jeu du joueur au moment de l'évaluation
      * @return True if the 'tempsDeJeuEnMinutes' field has been set, false otherwise.
      */
    public boolean hasTempsDeJeuEnMinutes() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'tempsDeJeuEnMinutes' field.
      * Temps de jeu du joueur au moment de l'évaluation
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearTempsDeJeuEnMinutes() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'versionJeuEvaluee' field.
      * Version du jeu lors de l'évaluation
      * @return The value.
      */
    public java.lang.CharSequence getVersionJeuEvaluee() {
      return versionJeuEvaluee;
    }


    /**
      * Sets the value of the 'versionJeuEvaluee' field.
      * Version du jeu lors de l'évaluation
      * @param value The value of 'versionJeuEvaluee'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setVersionJeuEvaluee(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.versionJeuEvaluee = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'versionJeuEvaluee' field has been set.
      * Version du jeu lors de l'évaluation
      * @return True if the 'versionJeuEvaluee' field has been set, false otherwise.
      */
    public boolean hasVersionJeuEvaluee() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'versionJeuEvaluee' field.
      * Version du jeu lors de l'évaluation
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearVersionJeuEvaluee() {
      versionJeuEvaluee = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'datePublication' field.
      * Date de publication de l'évaluation (epoch millis)
      * @return The value.
      */
    public long getDatePublication() {
      return datePublication;
    }


    /**
      * Sets the value of the 'datePublication' field.
      * Date de publication de l'évaluation (epoch millis)
      * @param value The value of 'datePublication'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setDatePublication(long value) {
      validate(fields()[11], value);
      this.datePublication = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'datePublication' field has been set.
      * Date de publication de l'évaluation (epoch millis)
      * @return True if the 'datePublication' field has been set, false otherwise.
      */
    public boolean hasDatePublication() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'datePublication' field.
      * Date de publication de l'évaluation (epoch millis)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearDatePublication() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'recommande' field.
      * True si le joueur recommande le jeu
      * @return The value.
      */
    public boolean getRecommande() {
      return recommande;
    }


    /**
      * Sets the value of the 'recommande' field.
      * True si le joueur recommande le jeu
      * @param value The value of 'recommande'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setRecommande(boolean value) {
      validate(fields()[12], value);
      this.recommande = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'recommande' field has been set.
      * True si le joueur recommande le jeu
      * @return True if the 'recommande' field has been set, false otherwise.
      */
    public boolean hasRecommande() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'recommande' field.
      * True si le joueur recommande le jeu
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearRecommande() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'aspectsPositifs' field.
      * Liste des aspects positifs mentionnés
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getAspectsPositifs() {
      return aspectsPositifs;
    }


    /**
      * Sets the value of the 'aspectsPositifs' field.
      * Liste des aspects positifs mentionnés
      * @param value The value of 'aspectsPositifs'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setAspectsPositifs(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[13], value);
      this.aspectsPositifs = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'aspectsPositifs' field has been set.
      * Liste des aspects positifs mentionnés
      * @return True if the 'aspectsPositifs' field has been set, false otherwise.
      */
    public boolean hasAspectsPositifs() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'aspectsPositifs' field.
      * Liste des aspects positifs mentionnés
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearAspectsPositifs() {
      aspectsPositifs = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'aspectsNegatifs' field.
      * Liste des aspects négatifs mentionnés
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getAspectsNegatifs() {
      return aspectsNegatifs;
    }


    /**
      * Sets the value of the 'aspectsNegatifs' field.
      * Liste des aspects négatifs mentionnés
      * @param value The value of 'aspectsNegatifs'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder setAspectsNegatifs(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[14], value);
      this.aspectsNegatifs = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'aspectsNegatifs' field has been set.
      * Liste des aspects négatifs mentionnés
      * @return True if the 'aspectsNegatifs' field has been set, false otherwise.
      */
    public boolean hasAspectsNegatifs() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'aspectsNegatifs' field.
      * Liste des aspects négatifs mentionnés
      * @return This builder.
      */
    public com.polysteam.plateforme.events.EvaluationEvent.Builder clearAspectsNegatifs() {
      aspectsNegatifs = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EvaluationEvent build() {
      try {
        EvaluationEvent record = new EvaluationEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.evaluationId = fieldSetFlags()[2] ? this.evaluationId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.jeuId = fieldSetFlags()[3] ? this.jeuId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.titreJeu = fieldSetFlags()[4] ? this.titreJeu : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.editeurId = fieldSetFlags()[5] ? this.editeurId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.pseudoJoueur = fieldSetFlags()[6] ? this.pseudoJoueur : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.note = fieldSetFlags()[7] ? this.note : (java.lang.Integer) defaultValue(fields()[7]);
        record.commentaire = fieldSetFlags()[8] ? this.commentaire : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.tempsDeJeuEnMinutes = fieldSetFlags()[9] ? this.tempsDeJeuEnMinutes : (java.lang.Long) defaultValue(fields()[9]);
        record.versionJeuEvaluee = fieldSetFlags()[10] ? this.versionJeuEvaluee : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.datePublication = fieldSetFlags()[11] ? this.datePublication : (java.lang.Long) defaultValue(fields()[11]);
        record.recommande = fieldSetFlags()[12] ? this.recommande : (java.lang.Boolean) defaultValue(fields()[12]);
        record.aspectsPositifs = fieldSetFlags()[13] ? this.aspectsPositifs : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[13]);
        record.aspectsNegatifs = fieldSetFlags()[14] ? this.aspectsNegatifs : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EvaluationEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<EvaluationEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EvaluationEvent>
    READER$ = (org.apache.avro.io.DatumReader<EvaluationEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.evaluationId);

    out.writeString(this.jeuId);

    out.writeString(this.titreJeu);

    out.writeString(this.editeurId);

    out.writeString(this.pseudoJoueur);

    out.writeInt(this.note);

    if (this.commentaire == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.commentaire);
    }

    out.writeLong(this.tempsDeJeuEnMinutes);

    out.writeString(this.versionJeuEvaluee);

    out.writeLong(this.datePublication);

    out.writeBoolean(this.recommande);

    long size0 = this.aspectsPositifs.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.aspectsPositifs) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    long size1 = this.aspectsNegatifs.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (java.lang.CharSequence e1: this.aspectsNegatifs) {
      actualSize1++;
      out.startItem();
      out.writeString(e1);
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.evaluationId = in.readString(this.evaluationId instanceof Utf8 ? (Utf8)this.evaluationId : null);

      this.jeuId = in.readString(this.jeuId instanceof Utf8 ? (Utf8)this.jeuId : null);

      this.titreJeu = in.readString(this.titreJeu instanceof Utf8 ? (Utf8)this.titreJeu : null);

      this.editeurId = in.readString(this.editeurId instanceof Utf8 ? (Utf8)this.editeurId : null);

      this.pseudoJoueur = in.readString(this.pseudoJoueur instanceof Utf8 ? (Utf8)this.pseudoJoueur : null);

      this.note = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.commentaire = null;
      } else {
        this.commentaire = in.readString(this.commentaire instanceof Utf8 ? (Utf8)this.commentaire : null);
      }

      this.tempsDeJeuEnMinutes = in.readLong();

      this.versionJeuEvaluee = in.readString(this.versionJeuEvaluee instanceof Utf8 ? (Utf8)this.versionJeuEvaluee : null);

      this.datePublication = in.readLong();

      this.recommande = in.readBoolean();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.aspectsPositifs;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("aspectsPositifs").schema());
        this.aspectsPositifs = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      long size1 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a1 = this.aspectsNegatifs;
      if (a1 == null) {
        a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("aspectsNegatifs").schema());
        this.aspectsNegatifs = a1;
      } else a1.clear();
      SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
          e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
          a1.add(e1);
        }
      }

    } else {
      for (int i = 0; i < 15; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.evaluationId = in.readString(this.evaluationId instanceof Utf8 ? (Utf8)this.evaluationId : null);
          break;

        case 3:
          this.jeuId = in.readString(this.jeuId instanceof Utf8 ? (Utf8)this.jeuId : null);
          break;

        case 4:
          this.titreJeu = in.readString(this.titreJeu instanceof Utf8 ? (Utf8)this.titreJeu : null);
          break;

        case 5:
          this.editeurId = in.readString(this.editeurId instanceof Utf8 ? (Utf8)this.editeurId : null);
          break;

        case 6:
          this.pseudoJoueur = in.readString(this.pseudoJoueur instanceof Utf8 ? (Utf8)this.pseudoJoueur : null);
          break;

        case 7:
          this.note = in.readInt();
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.commentaire = null;
          } else {
            this.commentaire = in.readString(this.commentaire instanceof Utf8 ? (Utf8)this.commentaire : null);
          }
          break;

        case 9:
          this.tempsDeJeuEnMinutes = in.readLong();
          break;

        case 10:
          this.versionJeuEvaluee = in.readString(this.versionJeuEvaluee instanceof Utf8 ? (Utf8)this.versionJeuEvaluee : null);
          break;

        case 11:
          this.datePublication = in.readLong();
          break;

        case 12:
          this.recommande = in.readBoolean();
          break;

        case 13:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.aspectsPositifs;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("aspectsPositifs").schema());
            this.aspectsPositifs = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 14:
          long size1 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a1 = this.aspectsNegatifs;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("aspectsNegatifs").schema());
            this.aspectsNegatifs = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
              a1.add(e1);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










