/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.polysteam.plateforme.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Événement émis par la plateforme vers un éditeur lors d'un crash/incident de jeu */
@org.apache.avro.specific.AvroGenerated
public class RapportIncidentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5429656538041643179L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RapportIncidentEvent\",\"namespace\":\"com.polysteam.plateforme.events\",\"doc\":\"Événement émis par la plateforme vers un éditeur lors d'un crash/incident de jeu\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"Identifiant unique de l'événement\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Timestamp de création de l'événement (epoch millis)\"},{\"name\":\"incidentId\",\"type\":\"string\",\"doc\":\"Identifiant unique de l'incident\"},{\"name\":\"jeuId\",\"type\":\"string\",\"doc\":\"Identifiant du jeu concerné\"},{\"name\":\"titreJeu\",\"type\":\"string\",\"doc\":\"Titre du jeu concerné\"},{\"name\":\"editeurId\",\"type\":\"string\",\"doc\":\"Identifiant de l'éditeur concerné\"},{\"name\":\"versionJeu\",\"type\":\"string\",\"doc\":\"Version du jeu lors de l'incident\"},{\"name\":\"plateforme\",\"type\":\"string\",\"doc\":\"Plateforme/OS sur laquelle l'incident s'est produit\"},{\"name\":\"pseudoJoueur\",\"type\":\"string\",\"doc\":\"Pseudo du joueur ayant rencontré l'incident\"},{\"name\":\"typeIncident\",\"type\":{\"type\":\"enum\",\"name\":\"TypeIncident\",\"symbols\":[\"CRASH\",\"FREEZE\",\"ERREUR_GRAPHIQUE\",\"ERREUR_SON\",\"ERREUR_SAUVEGARDE\",\"AUTRE\"]},\"doc\":\"Type d'incident rencontré\"},{\"name\":\"descriptionErreur\",\"type\":\"string\",\"doc\":\"Description détaillée de l'erreur (stacktrace, code erreur, etc.)\"},{\"name\":\"dateSurvenue\",\"type\":\"long\",\"doc\":\"Date/heure de survenue de l'incident (epoch millis)\"},{\"name\":\"contexte\",\"type\":[\"null\",\"string\"],\"doc\":\"Contexte de l'incident (action en cours, niveau, etc.)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RapportIncidentEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RapportIncidentEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RapportIncidentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RapportIncidentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RapportIncidentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RapportIncidentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RapportIncidentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RapportIncidentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RapportIncidentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identifiant unique de l'événement */
  private java.lang.CharSequence eventId;
  /** Timestamp de création de l'événement (epoch millis) */
  private long timestamp;
  /** Identifiant unique de l'incident */
  private java.lang.CharSequence incidentId;
  /** Identifiant du jeu concerné */
  private java.lang.CharSequence jeuId;
  /** Titre du jeu concerné */
  private java.lang.CharSequence titreJeu;
  /** Identifiant de l'éditeur concerné */
  private java.lang.CharSequence editeurId;
  /** Version du jeu lors de l'incident */
  private java.lang.CharSequence versionJeu;
  /** Plateforme/OS sur laquelle l'incident s'est produit */
  private java.lang.CharSequence plateforme;
  /** Pseudo du joueur ayant rencontré l'incident */
  private java.lang.CharSequence pseudoJoueur;
  /** Type d'incident rencontré */
  private com.polysteam.plateforme.events.TypeIncident typeIncident;
  /** Description détaillée de l'erreur (stacktrace, code erreur, etc.) */
  private java.lang.CharSequence descriptionErreur;
  /** Date/heure de survenue de l'incident (epoch millis) */
  private long dateSurvenue;
  /** Contexte de l'incident (action en cours, niveau, etc.) */
  private java.lang.CharSequence contexte;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RapportIncidentEvent() {}

  /**
   * All-args constructor.
   * @param eventId Identifiant unique de l'événement
   * @param timestamp Timestamp de création de l'événement (epoch millis)
   * @param incidentId Identifiant unique de l'incident
   * @param jeuId Identifiant du jeu concerné
   * @param titreJeu Titre du jeu concerné
   * @param editeurId Identifiant de l'éditeur concerné
   * @param versionJeu Version du jeu lors de l'incident
   * @param plateforme Plateforme/OS sur laquelle l'incident s'est produit
   * @param pseudoJoueur Pseudo du joueur ayant rencontré l'incident
   * @param typeIncident Type d'incident rencontré
   * @param descriptionErreur Description détaillée de l'erreur (stacktrace, code erreur, etc.)
   * @param dateSurvenue Date/heure de survenue de l'incident (epoch millis)
   * @param contexte Contexte de l'incident (action en cours, niveau, etc.)
   */
  public RapportIncidentEvent(java.lang.CharSequence eventId, java.lang.Long timestamp, java.lang.CharSequence incidentId, java.lang.CharSequence jeuId, java.lang.CharSequence titreJeu, java.lang.CharSequence editeurId, java.lang.CharSequence versionJeu, java.lang.CharSequence plateforme, java.lang.CharSequence pseudoJoueur, com.polysteam.plateforme.events.TypeIncident typeIncident, java.lang.CharSequence descriptionErreur, java.lang.Long dateSurvenue, java.lang.CharSequence contexte) {
    this.eventId = eventId;
    this.timestamp = timestamp;
    this.incidentId = incidentId;
    this.jeuId = jeuId;
    this.titreJeu = titreJeu;
    this.editeurId = editeurId;
    this.versionJeu = versionJeu;
    this.plateforme = plateforme;
    this.pseudoJoueur = pseudoJoueur;
    this.typeIncident = typeIncident;
    this.descriptionErreur = descriptionErreur;
    this.dateSurvenue = dateSurvenue;
    this.contexte = contexte;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return timestamp;
    case 2: return incidentId;
    case 3: return jeuId;
    case 4: return titreJeu;
    case 5: return editeurId;
    case 6: return versionJeu;
    case 7: return plateforme;
    case 8: return pseudoJoueur;
    case 9: return typeIncident;
    case 10: return descriptionErreur;
    case 11: return dateSurvenue;
    case 12: return contexte;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: incidentId = (java.lang.CharSequence)value$; break;
    case 3: jeuId = (java.lang.CharSequence)value$; break;
    case 4: titreJeu = (java.lang.CharSequence)value$; break;
    case 5: editeurId = (java.lang.CharSequence)value$; break;
    case 6: versionJeu = (java.lang.CharSequence)value$; break;
    case 7: plateforme = (java.lang.CharSequence)value$; break;
    case 8: pseudoJoueur = (java.lang.CharSequence)value$; break;
    case 9: typeIncident = (com.polysteam.plateforme.events.TypeIncident)value$; break;
    case 10: descriptionErreur = (java.lang.CharSequence)value$; break;
    case 11: dateSurvenue = (java.lang.Long)value$; break;
    case 12: contexte = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return Identifiant unique de l'événement
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * Identifiant unique de l'événement
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp de création de l'événement (epoch millis)
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp de création de l'événement (epoch millis)
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'incidentId' field.
   * @return Identifiant unique de l'incident
   */
  public java.lang.CharSequence getIncidentId() {
    return incidentId;
  }


  /**
   * Sets the value of the 'incidentId' field.
   * Identifiant unique de l'incident
   * @param value the value to set.
   */
  public void setIncidentId(java.lang.CharSequence value) {
    this.incidentId = value;
  }

  /**
   * Gets the value of the 'jeuId' field.
   * @return Identifiant du jeu concerné
   */
  public java.lang.CharSequence getJeuId() {
    return jeuId;
  }


  /**
   * Sets the value of the 'jeuId' field.
   * Identifiant du jeu concerné
   * @param value the value to set.
   */
  public void setJeuId(java.lang.CharSequence value) {
    this.jeuId = value;
  }

  /**
   * Gets the value of the 'titreJeu' field.
   * @return Titre du jeu concerné
   */
  public java.lang.CharSequence getTitreJeu() {
    return titreJeu;
  }


  /**
   * Sets the value of the 'titreJeu' field.
   * Titre du jeu concerné
   * @param value the value to set.
   */
  public void setTitreJeu(java.lang.CharSequence value) {
    this.titreJeu = value;
  }

  /**
   * Gets the value of the 'editeurId' field.
   * @return Identifiant de l'éditeur concerné
   */
  public java.lang.CharSequence getEditeurId() {
    return editeurId;
  }


  /**
   * Sets the value of the 'editeurId' field.
   * Identifiant de l'éditeur concerné
   * @param value the value to set.
   */
  public void setEditeurId(java.lang.CharSequence value) {
    this.editeurId = value;
  }

  /**
   * Gets the value of the 'versionJeu' field.
   * @return Version du jeu lors de l'incident
   */
  public java.lang.CharSequence getVersionJeu() {
    return versionJeu;
  }


  /**
   * Sets the value of the 'versionJeu' field.
   * Version du jeu lors de l'incident
   * @param value the value to set.
   */
  public void setVersionJeu(java.lang.CharSequence value) {
    this.versionJeu = value;
  }

  /**
   * Gets the value of the 'plateforme' field.
   * @return Plateforme/OS sur laquelle l'incident s'est produit
   */
  public java.lang.CharSequence getPlateforme() {
    return plateforme;
  }


  /**
   * Sets the value of the 'plateforme' field.
   * Plateforme/OS sur laquelle l'incident s'est produit
   * @param value the value to set.
   */
  public void setPlateforme(java.lang.CharSequence value) {
    this.plateforme = value;
  }

  /**
   * Gets the value of the 'pseudoJoueur' field.
   * @return Pseudo du joueur ayant rencontré l'incident
   */
  public java.lang.CharSequence getPseudoJoueur() {
    return pseudoJoueur;
  }


  /**
   * Sets the value of the 'pseudoJoueur' field.
   * Pseudo du joueur ayant rencontré l'incident
   * @param value the value to set.
   */
  public void setPseudoJoueur(java.lang.CharSequence value) {
    this.pseudoJoueur = value;
  }

  /**
   * Gets the value of the 'typeIncident' field.
   * @return Type d'incident rencontré
   */
  public com.polysteam.plateforme.events.TypeIncident getTypeIncident() {
    return typeIncident;
  }


  /**
   * Sets the value of the 'typeIncident' field.
   * Type d'incident rencontré
   * @param value the value to set.
   */
  public void setTypeIncident(com.polysteam.plateforme.events.TypeIncident value) {
    this.typeIncident = value;
  }

  /**
   * Gets the value of the 'descriptionErreur' field.
   * @return Description détaillée de l'erreur (stacktrace, code erreur, etc.)
   */
  public java.lang.CharSequence getDescriptionErreur() {
    return descriptionErreur;
  }


  /**
   * Sets the value of the 'descriptionErreur' field.
   * Description détaillée de l'erreur (stacktrace, code erreur, etc.)
   * @param value the value to set.
   */
  public void setDescriptionErreur(java.lang.CharSequence value) {
    this.descriptionErreur = value;
  }

  /**
   * Gets the value of the 'dateSurvenue' field.
   * @return Date/heure de survenue de l'incident (epoch millis)
   */
  public long getDateSurvenue() {
    return dateSurvenue;
  }


  /**
   * Sets the value of the 'dateSurvenue' field.
   * Date/heure de survenue de l'incident (epoch millis)
   * @param value the value to set.
   */
  public void setDateSurvenue(long value) {
    this.dateSurvenue = value;
  }

  /**
   * Gets the value of the 'contexte' field.
   * @return Contexte de l'incident (action en cours, niveau, etc.)
   */
  public java.lang.CharSequence getContexte() {
    return contexte;
  }


  /**
   * Sets the value of the 'contexte' field.
   * Contexte de l'incident (action en cours, niveau, etc.)
   * @param value the value to set.
   */
  public void setContexte(java.lang.CharSequence value) {
    this.contexte = value;
  }

  /**
   * Creates a new RapportIncidentEvent RecordBuilder.
   * @return A new RapportIncidentEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.RapportIncidentEvent.Builder newBuilder() {
    return new com.polysteam.plateforme.events.RapportIncidentEvent.Builder();
  }

  /**
   * Creates a new RapportIncidentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RapportIncidentEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.RapportIncidentEvent.Builder newBuilder(com.polysteam.plateforme.events.RapportIncidentEvent.Builder other) {
    if (other == null) {
      return new com.polysteam.plateforme.events.RapportIncidentEvent.Builder();
    } else {
      return new com.polysteam.plateforme.events.RapportIncidentEvent.Builder(other);
    }
  }

  /**
   * Creates a new RapportIncidentEvent RecordBuilder by copying an existing RapportIncidentEvent instance.
   * @param other The existing instance to copy.
   * @return A new RapportIncidentEvent RecordBuilder
   */
  public static com.polysteam.plateforme.events.RapportIncidentEvent.Builder newBuilder(com.polysteam.plateforme.events.RapportIncidentEvent other) {
    if (other == null) {
      return new com.polysteam.plateforme.events.RapportIncidentEvent.Builder();
    } else {
      return new com.polysteam.plateforme.events.RapportIncidentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RapportIncidentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RapportIncidentEvent>
    implements org.apache.avro.data.RecordBuilder<RapportIncidentEvent> {

    /** Identifiant unique de l'événement */
    private java.lang.CharSequence eventId;
    /** Timestamp de création de l'événement (epoch millis) */
    private long timestamp;
    /** Identifiant unique de l'incident */
    private java.lang.CharSequence incidentId;
    /** Identifiant du jeu concerné */
    private java.lang.CharSequence jeuId;
    /** Titre du jeu concerné */
    private java.lang.CharSequence titreJeu;
    /** Identifiant de l'éditeur concerné */
    private java.lang.CharSequence editeurId;
    /** Version du jeu lors de l'incident */
    private java.lang.CharSequence versionJeu;
    /** Plateforme/OS sur laquelle l'incident s'est produit */
    private java.lang.CharSequence plateforme;
    /** Pseudo du joueur ayant rencontré l'incident */
    private java.lang.CharSequence pseudoJoueur;
    /** Type d'incident rencontré */
    private com.polysteam.plateforme.events.TypeIncident typeIncident;
    /** Description détaillée de l'erreur (stacktrace, code erreur, etc.) */
    private java.lang.CharSequence descriptionErreur;
    /** Date/heure de survenue de l'incident (epoch millis) */
    private long dateSurvenue;
    /** Contexte de l'incident (action en cours, niveau, etc.) */
    private java.lang.CharSequence contexte;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.polysteam.plateforme.events.RapportIncidentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[2].schema(), other.incidentId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.jeuId)) {
        this.jeuId = data().deepCopy(fields()[3].schema(), other.jeuId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.titreJeu)) {
        this.titreJeu = data().deepCopy(fields()[4].schema(), other.titreJeu);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.editeurId)) {
        this.editeurId = data().deepCopy(fields()[5].schema(), other.editeurId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.versionJeu)) {
        this.versionJeu = data().deepCopy(fields()[6].schema(), other.versionJeu);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.plateforme)) {
        this.plateforme = data().deepCopy(fields()[7].schema(), other.plateforme);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.pseudoJoueur)) {
        this.pseudoJoueur = data().deepCopy(fields()[8].schema(), other.pseudoJoueur);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.typeIncident)) {
        this.typeIncident = data().deepCopy(fields()[9].schema(), other.typeIncident);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.descriptionErreur)) {
        this.descriptionErreur = data().deepCopy(fields()[10].schema(), other.descriptionErreur);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.dateSurvenue)) {
        this.dateSurvenue = data().deepCopy(fields()[11].schema(), other.dateSurvenue);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.contexte)) {
        this.contexte = data().deepCopy(fields()[12].schema(), other.contexte);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing RapportIncidentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.polysteam.plateforme.events.RapportIncidentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.incidentId)) {
        this.incidentId = data().deepCopy(fields()[2].schema(), other.incidentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.jeuId)) {
        this.jeuId = data().deepCopy(fields()[3].schema(), other.jeuId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.titreJeu)) {
        this.titreJeu = data().deepCopy(fields()[4].schema(), other.titreJeu);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.editeurId)) {
        this.editeurId = data().deepCopy(fields()[5].schema(), other.editeurId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.versionJeu)) {
        this.versionJeu = data().deepCopy(fields()[6].schema(), other.versionJeu);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.plateforme)) {
        this.plateforme = data().deepCopy(fields()[7].schema(), other.plateforme);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.pseudoJoueur)) {
        this.pseudoJoueur = data().deepCopy(fields()[8].schema(), other.pseudoJoueur);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.typeIncident)) {
        this.typeIncident = data().deepCopy(fields()[9].schema(), other.typeIncident);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.descriptionErreur)) {
        this.descriptionErreur = data().deepCopy(fields()[10].schema(), other.descriptionErreur);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.dateSurvenue)) {
        this.dateSurvenue = data().deepCopy(fields()[11].schema(), other.dateSurvenue);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.contexte)) {
        this.contexte = data().deepCopy(fields()[12].schema(), other.contexte);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * Identifiant unique de l'événement
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * Identifiant unique de l'événement
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp de création de l'événement (epoch millis)
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp de création de l'événement (epoch millis)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'incidentId' field.
      * Identifiant unique de l'incident
      * @return The value.
      */
    public java.lang.CharSequence getIncidentId() {
      return incidentId;
    }


    /**
      * Sets the value of the 'incidentId' field.
      * Identifiant unique de l'incident
      * @param value The value of 'incidentId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setIncidentId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.incidentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'incidentId' field has been set.
      * Identifiant unique de l'incident
      * @return True if the 'incidentId' field has been set, false otherwise.
      */
    public boolean hasIncidentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'incidentId' field.
      * Identifiant unique de l'incident
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearIncidentId() {
      incidentId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'jeuId' field.
      * Identifiant du jeu concerné
      * @return The value.
      */
    public java.lang.CharSequence getJeuId() {
      return jeuId;
    }


    /**
      * Sets the value of the 'jeuId' field.
      * Identifiant du jeu concerné
      * @param value The value of 'jeuId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setJeuId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.jeuId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'jeuId' field has been set.
      * Identifiant du jeu concerné
      * @return True if the 'jeuId' field has been set, false otherwise.
      */
    public boolean hasJeuId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'jeuId' field.
      * Identifiant du jeu concerné
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearJeuId() {
      jeuId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'titreJeu' field.
      * Titre du jeu concerné
      * @return The value.
      */
    public java.lang.CharSequence getTitreJeu() {
      return titreJeu;
    }


    /**
      * Sets the value of the 'titreJeu' field.
      * Titre du jeu concerné
      * @param value The value of 'titreJeu'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setTitreJeu(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.titreJeu = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'titreJeu' field has been set.
      * Titre du jeu concerné
      * @return True if the 'titreJeu' field has been set, false otherwise.
      */
    public boolean hasTitreJeu() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'titreJeu' field.
      * Titre du jeu concerné
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearTitreJeu() {
      titreJeu = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @return The value.
      */
    public java.lang.CharSequence getEditeurId() {
      return editeurId;
    }


    /**
      * Sets the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @param value The value of 'editeurId'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setEditeurId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.editeurId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'editeurId' field has been set.
      * Identifiant de l'éditeur concerné
      * @return True if the 'editeurId' field has been set, false otherwise.
      */
    public boolean hasEditeurId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'editeurId' field.
      * Identifiant de l'éditeur concerné
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearEditeurId() {
      editeurId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'versionJeu' field.
      * Version du jeu lors de l'incident
      * @return The value.
      */
    public java.lang.CharSequence getVersionJeu() {
      return versionJeu;
    }


    /**
      * Sets the value of the 'versionJeu' field.
      * Version du jeu lors de l'incident
      * @param value The value of 'versionJeu'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setVersionJeu(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.versionJeu = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'versionJeu' field has been set.
      * Version du jeu lors de l'incident
      * @return True if the 'versionJeu' field has been set, false otherwise.
      */
    public boolean hasVersionJeu() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'versionJeu' field.
      * Version du jeu lors de l'incident
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearVersionJeu() {
      versionJeu = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'plateforme' field.
      * Plateforme/OS sur laquelle l'incident s'est produit
      * @return The value.
      */
    public java.lang.CharSequence getPlateforme() {
      return plateforme;
    }


    /**
      * Sets the value of the 'plateforme' field.
      * Plateforme/OS sur laquelle l'incident s'est produit
      * @param value The value of 'plateforme'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setPlateforme(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.plateforme = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'plateforme' field has been set.
      * Plateforme/OS sur laquelle l'incident s'est produit
      * @return True if the 'plateforme' field has been set, false otherwise.
      */
    public boolean hasPlateforme() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'plateforme' field.
      * Plateforme/OS sur laquelle l'incident s'est produit
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearPlateforme() {
      plateforme = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'pseudoJoueur' field.
      * Pseudo du joueur ayant rencontré l'incident
      * @return The value.
      */
    public java.lang.CharSequence getPseudoJoueur() {
      return pseudoJoueur;
    }


    /**
      * Sets the value of the 'pseudoJoueur' field.
      * Pseudo du joueur ayant rencontré l'incident
      * @param value The value of 'pseudoJoueur'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setPseudoJoueur(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.pseudoJoueur = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'pseudoJoueur' field has been set.
      * Pseudo du joueur ayant rencontré l'incident
      * @return True if the 'pseudoJoueur' field has been set, false otherwise.
      */
    public boolean hasPseudoJoueur() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'pseudoJoueur' field.
      * Pseudo du joueur ayant rencontré l'incident
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearPseudoJoueur() {
      pseudoJoueur = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'typeIncident' field.
      * Type d'incident rencontré
      * @return The value.
      */
    public com.polysteam.plateforme.events.TypeIncident getTypeIncident() {
      return typeIncident;
    }


    /**
      * Sets the value of the 'typeIncident' field.
      * Type d'incident rencontré
      * @param value The value of 'typeIncident'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setTypeIncident(com.polysteam.plateforme.events.TypeIncident value) {
      validate(fields()[9], value);
      this.typeIncident = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'typeIncident' field has been set.
      * Type d'incident rencontré
      * @return True if the 'typeIncident' field has been set, false otherwise.
      */
    public boolean hasTypeIncident() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'typeIncident' field.
      * Type d'incident rencontré
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearTypeIncident() {
      typeIncident = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'descriptionErreur' field.
      * Description détaillée de l'erreur (stacktrace, code erreur, etc.)
      * @return The value.
      */
    public java.lang.CharSequence getDescriptionErreur() {
      return descriptionErreur;
    }


    /**
      * Sets the value of the 'descriptionErreur' field.
      * Description détaillée de l'erreur (stacktrace, code erreur, etc.)
      * @param value The value of 'descriptionErreur'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setDescriptionErreur(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.descriptionErreur = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'descriptionErreur' field has been set.
      * Description détaillée de l'erreur (stacktrace, code erreur, etc.)
      * @return True if the 'descriptionErreur' field has been set, false otherwise.
      */
    public boolean hasDescriptionErreur() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'descriptionErreur' field.
      * Description détaillée de l'erreur (stacktrace, code erreur, etc.)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearDescriptionErreur() {
      descriptionErreur = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateSurvenue' field.
      * Date/heure de survenue de l'incident (epoch millis)
      * @return The value.
      */
    public long getDateSurvenue() {
      return dateSurvenue;
    }


    /**
      * Sets the value of the 'dateSurvenue' field.
      * Date/heure de survenue de l'incident (epoch millis)
      * @param value The value of 'dateSurvenue'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setDateSurvenue(long value) {
      validate(fields()[11], value);
      this.dateSurvenue = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'dateSurvenue' field has been set.
      * Date/heure de survenue de l'incident (epoch millis)
      * @return True if the 'dateSurvenue' field has been set, false otherwise.
      */
    public boolean hasDateSurvenue() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'dateSurvenue' field.
      * Date/heure de survenue de l'incident (epoch millis)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearDateSurvenue() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'contexte' field.
      * Contexte de l'incident (action en cours, niveau, etc.)
      * @return The value.
      */
    public java.lang.CharSequence getContexte() {
      return contexte;
    }


    /**
      * Sets the value of the 'contexte' field.
      * Contexte de l'incident (action en cours, niveau, etc.)
      * @param value The value of 'contexte'.
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder setContexte(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.contexte = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'contexte' field has been set.
      * Contexte de l'incident (action en cours, niveau, etc.)
      * @return True if the 'contexte' field has been set, false otherwise.
      */
    public boolean hasContexte() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'contexte' field.
      * Contexte de l'incident (action en cours, niveau, etc.)
      * @return This builder.
      */
    public com.polysteam.plateforme.events.RapportIncidentEvent.Builder clearContexte() {
      contexte = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RapportIncidentEvent build() {
      try {
        RapportIncidentEvent record = new RapportIncidentEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.incidentId = fieldSetFlags()[2] ? this.incidentId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.jeuId = fieldSetFlags()[3] ? this.jeuId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.titreJeu = fieldSetFlags()[4] ? this.titreJeu : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.editeurId = fieldSetFlags()[5] ? this.editeurId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.versionJeu = fieldSetFlags()[6] ? this.versionJeu : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.plateforme = fieldSetFlags()[7] ? this.plateforme : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.pseudoJoueur = fieldSetFlags()[8] ? this.pseudoJoueur : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.typeIncident = fieldSetFlags()[9] ? this.typeIncident : (com.polysteam.plateforme.events.TypeIncident) defaultValue(fields()[9]);
        record.descriptionErreur = fieldSetFlags()[10] ? this.descriptionErreur : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.dateSurvenue = fieldSetFlags()[11] ? this.dateSurvenue : (java.lang.Long) defaultValue(fields()[11]);
        record.contexte = fieldSetFlags()[12] ? this.contexte : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RapportIncidentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RapportIncidentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RapportIncidentEvent>
    READER$ = (org.apache.avro.io.DatumReader<RapportIncidentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeLong(this.timestamp);

    out.writeString(this.incidentId);

    out.writeString(this.jeuId);

    out.writeString(this.titreJeu);

    out.writeString(this.editeurId);

    out.writeString(this.versionJeu);

    out.writeString(this.plateforme);

    out.writeString(this.pseudoJoueur);

    out.writeEnum(this.typeIncident.ordinal());

    out.writeString(this.descriptionErreur);

    out.writeLong(this.dateSurvenue);

    if (this.contexte == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.contexte);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.timestamp = in.readLong();

      this.incidentId = in.readString(this.incidentId instanceof Utf8 ? (Utf8)this.incidentId : null);

      this.jeuId = in.readString(this.jeuId instanceof Utf8 ? (Utf8)this.jeuId : null);

      this.titreJeu = in.readString(this.titreJeu instanceof Utf8 ? (Utf8)this.titreJeu : null);

      this.editeurId = in.readString(this.editeurId instanceof Utf8 ? (Utf8)this.editeurId : null);

      this.versionJeu = in.readString(this.versionJeu instanceof Utf8 ? (Utf8)this.versionJeu : null);

      this.plateforme = in.readString(this.plateforme instanceof Utf8 ? (Utf8)this.plateforme : null);

      this.pseudoJoueur = in.readString(this.pseudoJoueur instanceof Utf8 ? (Utf8)this.pseudoJoueur : null);

      this.typeIncident = com.polysteam.plateforme.events.TypeIncident.values()[in.readEnum()];

      this.descriptionErreur = in.readString(this.descriptionErreur instanceof Utf8 ? (Utf8)this.descriptionErreur : null);

      this.dateSurvenue = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.contexte = null;
      } else {
        this.contexte = in.readString(this.contexte instanceof Utf8 ? (Utf8)this.contexte : null);
      }

    } else {
      for (int i = 0; i < 13; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.incidentId = in.readString(this.incidentId instanceof Utf8 ? (Utf8)this.incidentId : null);
          break;

        case 3:
          this.jeuId = in.readString(this.jeuId instanceof Utf8 ? (Utf8)this.jeuId : null);
          break;

        case 4:
          this.titreJeu = in.readString(this.titreJeu instanceof Utf8 ? (Utf8)this.titreJeu : null);
          break;

        case 5:
          this.editeurId = in.readString(this.editeurId instanceof Utf8 ? (Utf8)this.editeurId : null);
          break;

        case 6:
          this.versionJeu = in.readString(this.versionJeu instanceof Utf8 ? (Utf8)this.versionJeu : null);
          break;

        case 7:
          this.plateforme = in.readString(this.plateforme instanceof Utf8 ? (Utf8)this.plateforme : null);
          break;

        case 8:
          this.pseudoJoueur = in.readString(this.pseudoJoueur instanceof Utf8 ? (Utf8)this.pseudoJoueur : null);
          break;

        case 9:
          this.typeIncident = com.polysteam.plateforme.events.TypeIncident.values()[in.readEnum()];
          break;

        case 10:
          this.descriptionErreur = in.readString(this.descriptionErreur instanceof Utf8 ? (Utf8)this.descriptionErreur : null);
          break;

        case 11:
          this.dateSurvenue = in.readLong();
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.contexte = null;
          } else {
            this.contexte = in.readString(this.contexte instanceof Utf8 ? (Utf8)this.contexte : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










