/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.polysteam.plateforme.events;
@org.apache.avro.specific.AvroGenerated
public enum TypeIncident implements org.apache.avro.generic.GenericEnumSymbol<TypeIncident> {
  CRASH, FREEZE, ERREUR_GRAPHIQUE, ERREUR_SON, ERREUR_SAUVEGARDE, AUTRE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TypeIncident\",\"namespace\":\"com.polysteam.plateforme.events\",\"symbols\":[\"CRASH\",\"FREEZE\",\"ERREUR_GRAPHIQUE\",\"ERREUR_SON\",\"ERREUR_SAUVEGARDE\",\"AUTRE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
